Repository ingenieria-software-7009-2025-2/city-lens-api, pull requests merged in 2025-04, with the labels that each got.

#26 fix(cl13): corrección script de iniciación.
  src/main/sql/demo/locations.sql
  src/main/sql/demo/users.sql
  src/main/sql/schema.sql
  src/main/sql/setup/city_lens_bd_scheme.png
  src/main/sql/setup/schema.sql
  src/main/sql/setup/setup.sql
  src/main/sql/utils/functions/check_duplicate_location.sql
  src/main/sql/utils/functions/enforce_moderation_role.sql
  src/main/sql/utils/functions/search_reports_by_zipcode.sql
  src/main/sql/utils/procedures/create_report.sql
  src/main/sql/utils/procedures/get_active_reports.sql
  src/main/sql/utils/procedures/get_recently_resolved_reports.sql
  src/main/sql/utils/triggers/check_moderator_before_insert.sql
Labels: bug, enhancement, refactor

#27 [test]feat(cl-14): Endpoints para creación de reportes
  src/main/kotlin/com/aperture_science/city_lens_api/location/controller/LocationController.kt
  src/main/kotlin/com/aperture_science/city_lens_api/location/controller/body/LocationCreateBody.kt
  src/main/kotlin/com/aperture_science/city_lens_api/location/controller/body/LocationMinimalBody.kt
  src/main/kotlin/com/aperture_science/city_lens_api/location/controller/body/LocationOutputBody.kt
  src/main/kotlin/com/aperture_science/city_lens_api/location/controller/body/LocationUpdateBody.kt
  src/main/kotlin/com/aperture_science/city_lens_api/location/repository/LocationRepository.kt
  src/main/kotlin/com/aperture_science/city_lens_api/location/repository/entity/Localizacion.kt
  src/main/kotlin/com/aperture_science/city_lens_api/location/service/LocationService.kt
  src/main/kotlin/com/aperture_science/city_lens_api/report/controller/ReportController.kt
  src/main/kotlin/com/aperture_science/city_lens_api/report/controller/body/ReportCreateBody.kt
  src/main/kotlin/com/aperture_science/city_lens_api/report/controller/body/ReportOutputBody.kt
  src/main/kotlin/com/aperture_science/city_lens_api/report/controller/body/ReportUpdateBody.kt
  src/main/kotlin/com/aperture_science/city_lens_api/report/repository/ReportRepository.kt
  src/main/kotlin/com/aperture_science/city_lens_api/report/repository/entity/Reporte.kt
  src/main/kotlin/com/aperture_science/city_lens_api/report/service/ReportService.kt
  src/main/kotlin/com/aperture_science/city_lens_api/user/controller/UsuarioController.kt
  src/main/kotlin/com/aperture_science/city_lens_api/user/repository/entity/SessionToken.kt
  src/main/kotlin/com/aperture_science/city_lens_api/user/service/UsuarioService.kt
Labels: enhancement

#33 docs(cl-24):Documentacion en repository y service
  src/main/kotlin/com/aperture_science/city_lens_api/report/repository/ReportRepository.kt
  src/main/kotlin/com/aperture_science/city_lens_api/report/repository/entity/Image.kt
  src/main/kotlin/com/aperture_science/city_lens_api/report/repository/entity/Location.kt
  src/main/kotlin/com/aperture_science/city_lens_api/report/repository/entity/Reporte.kt
  src/main/kotlin/com/aperture_science/city_lens_api/report/service/ReportService.kt
Labels: documentation

#34 docs(CL-15): actualización de documentación Swagger
  src/main/kotlin/com/aperture_science/city_lens_api/location/controller/LocationController.kt
  src/main/kotlin/com/aperture_science/city_lens_api/report/controller/ReportController.kt
Labels: documentation

#37 fix: error en endpoint de report/delete solucionado para interactuar con front end
  src/main/kotlin/com/aperture_science/city_lens_api/report/controller/ReportController.kt
Labels: bug
