Repository ingenieria-software-7009-2025-2/city-lens-api, pull requests merged in 2025-03, with the labels that each got.

#2 feat: Esquema ER de la BD + creación de tablas en scheme.sql
  src/main/sql/city_lens_bd_scheme.png
  src/main/sql/schema.sql
Labels: enhancement

#3 fix: falta de atributo 'password' en la tabla users
  src/main/sql/city_lens_bd_scheme.png
  src/main/sql/schema.sql
Labels: bug, enhancement

#8 fix: Esquema en scheme.sql con error por tabla 'user'
  src/main/sql/schema.sql
Labels: bug, enhancement

#5 Eliminacion Mascota
  src/main/kotlin/com/aperture_science/city_lens_api/mascota/Mascota.kt
  src/main/kotlin/com/aperture_science/city_lens_api/mascota/MascotaBody.kt
  src/main/kotlin/com/aperture_science/city_lens_api/mascota/MascotaController.kt
Labels: refactor

#9 Fixed database name incompatibilities for the registration
  src/main/kotlin/com/aperture_science/city_lens_api/user/controller/UsuarioController.kt
  src/main/kotlin/com/aperture_science/city_lens_api/user/repository/entity/SessionToken.kt
  src/main/kotlin/com/aperture_science/city_lens_api/user/repository/entity/Usuario.kt
  src/main/resources/META-INF/persistence.xml
Labels: enhancement

#11 docs: Documentación general del proyecto
  README.md
  pom.xml
  src/main/kotlin/com/aperture_science/city_lens_api/CityLensApiApplication.kt
  src/main/kotlin/com/aperture_science/city_lens_api/UsuarioRegisterBody.kt
  src/main/kotlin/com/aperture_science/city_lens_api/modules/config/framework/controller/HealthController.kt
  src/main/kotlin/com/aperture_science/city_lens_api/user/controller/body/UsuarioLoginBody.kt
  src/main/kotlin/com/aperture_science/city_lens_api/user/controller/body/UsuarioLoginOutputBody.kt
  src/main/kotlin/com/aperture_science/city_lens_api/user/repository/entity/SessionToken.kt
  src/main/kotlin/com/aperture_science/city_lens_api/user/repository/entity/Usuario.kt
  src/main/kotlin/com/aperture_science/city_lens_api/util/EntityManagerFactoryInstance.kt
  src/main/kotlin/com/aperture_science/city_lens_api/util/HashUtil.kt
  src/main/resources/application.properties
  src/main/sql/schema.sql
  src/main/sql/setup.sql
Labels: documentation

#10 Added the final functionalities for the user (Could not test)
  src/main/kotlin/com/aperture_science/city_lens_api/user/controller/UsuarioController.kt
Labels: enhancement

#12 fix: Correciones en los endpoints para Me, Login y Logout.
  city-lens-api.postman_collection.json
  src/main/kotlin/com/aperture_science/city_lens_api/user/controller/UsuarioController.kt
  src/main/kotlin/com/aperture_science/city_lens_api/user/controller/body/UsuarioPutMeBody.kt
  src/main/kotlin/com/aperture_science/city_lens_api/user/repository/entity/SessionToken.kt
Labels: documentation, enhancement

#13 Code refactor
  documentacion/DocumentacionCarpetas.md
  documentacion/DocumentacionCarpetas.pdf
  src/main/kotlin/com/aperture_science/city_lens_api/user/controller/UsuarioController.kt
  src/main/kotlin/com/aperture_science/city_lens_api/user/controller/body/UsuarioRegisterBody.kt
  src/main/kotlin/com/aperture_science/city_lens_api/user/repository/UsuarioRepository.kt
  src/main/kotlin/com/aperture_science/city_lens_api/user/service/UsuarioService.kt
Labels: refactor

#14 docs(tar27): plantillas de issues/prs
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/petición-sugerencia-de-funcionalidad-.md
  .github/ISSUE_TEMPLATE/reporte-de-bug.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: documentation

#15 refactor(tar20): arquitectura Backend / docs:(tar27): plantillas de issues/prs
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/petición-sugerencia-de-funcionalidad-.md
  .github/ISSUE_TEMPLATE/reporte-de-bug.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  documentacion/DocumentacionCarpetas.md
  documentacion/DocumentacionCarpetas.pdf
  src/main/kotlin/com/aperture_science/city_lens_api/user/controller/UsuarioController.kt
  src/main/kotlin/com/aperture_science/city_lens_api/user/controller/body/UsuarioRegisterBody.kt
  src/main/kotlin/com/aperture_science/city_lens_api/user/repository/UsuarioRepository.kt
  src/main/kotlin/com/aperture_science/city_lens_api/user/service/UsuarioService.kt
Labels: documentation, refactor

#19 Removido password de la respuesta del login y Arreglado Hashing en /v…
  src/main/kotlin/com/aperture_science/city_lens_api/user/controller/body/UsuarioLoginOutputBody.kt
  src/main/kotlin/com/aperture_science/city_lens_api/user/controller/body/UsuarioLoginOutputUser.kt
  src/main/kotlin/com/aperture_science/city_lens_api/user/repository/UsuarioRepository.kt
  src/main/kotlin/com/aperture_science/city_lens_api/user/service/UsuarioService.kt
Labels: bug

#20 Quickfix: Password hashes were re-hashing on user updates
  src/main/kotlin/com/aperture_science/city_lens_api/user/repository/UsuarioRepository.kt
Labels: bug

#23 feat(tar29): configuración de CORS para conexión de endpoints
  src/main/kotlin/com/aperture_science/city_lens_api/config/CorsConfig.kt
  src/main/kotlin/com/aperture_science/city_lens_api/user/service/UsuarioService.kt
Labels: enhancement

#24 docs(tar-43):doc para consistencia de archivos
  documentacion/V.0.1/City_Lens_Requerimientos_del_Proyecto.md
  documentacion/V.0.1/City_Lens_Requerimientos_del_Proyecto.pdf
  documentacion/V.0.1/DocumentacionCarpetas.md
  documentacion/V.0.1/DocumentacionCarpetas.pdf
  documentacion/V.1.0/CasosDeUso.pdf
  documentacion/V.1.0/Diagramas/DF_ActualizarDatos.png
  documentacion/V.1.0/Diagramas/DF_CerrarSesion.png
  documentacion/V.1.0/Diagramas/DF_ConsultarInfo.png
  documentacion/V.1.0/Diagramas/DF_InicioSesion.png
  documentacion/V.1.0/Diagramas/DF_RegistrarSesion.png
  documentacion/V.1.0/Diagramas/DiagramaUML.png
Labels: documentation

#25 feat(tar32): lanzamiento v1.0.0
  README.md
  documentacion/V.0.1/City_Lens_Requerimientos_del_Proyecto.md
  documentacion/V.0.1/City_Lens_Requerimientos_del_Proyecto.pdf
  documentacion/V.0.1/DocumentacionCarpetas.md
  documentacion/V.0.1/DocumentacionCarpetas.pdf
  documentacion/V.1.0/CasosDeUso.pdf
  documentacion/V.1.0/Diagramas/DF_ActualizarDatos.png
  documentacion/V.1.0/Diagramas/DF_CerrarSesion.png
  documentacion/V.1.0/Diagramas/DF_ConsultarInfo.png
  documentacion/V.1.0/Diagramas/DF_InicioSesion.png
  documentacion/V.1.0/Diagramas/DF_RegistrarSesion.png
  documentacion/V.1.0/Diagramas/DiagramaUML.png
  pom.xml
  src/main/kotlin/com/aperture_science/city_lens_api/CityLensApiApplication.kt
  src/main/kotlin/com/aperture_science/city_lens_api/config/CorsConfig.kt
  src/main/kotlin/com/aperture_science/city_lens_api/config/SwaggerConfig.kt
  src/main/kotlin/com/aperture_science/city_lens_api/modules/config/framework/controller/HealthController.kt
  src/main/kotlin/com/aperture_science/city_lens_api/user/controller/UsuarioController.kt
  src/main/kotlin/com/aperture_science/city_lens_api/user/controller/body/UsuarioLoginOutputBody.kt
  src/main/kotlin/com/aperture_science/city_lens_api/user/controller/body/UsuarioLoginOutputUser.kt
  src/main/kotlin/com/aperture_science/city_lens_api/user/repository/UsuarioRepository.kt
  src/main/kotlin/com/aperture_science/city_lens_api/user/service/UsuarioService.kt
  src/main/resources/application.properties
Labels: enhancement
